### ISSUE TITLE
What are 3 things to keep in mind when teaching beginners web development?

### ISSUE THREAD

**Issue by wesbos** [drewminns/ama#1]
You have trained hundreds of students and are extremely helpful and patient with them. What are your secrets?

**Comment by drewminns** [comment]
I'd like to thank my parents for the patient and helpful part actually!

Truthfully though, it comes from an excitement with the industry. I was able to go from some punk kid that loved messing around in Illustrator and Photoshop, into creating projects that affected people. This industry is like a 'no-parents' zone, we have the freedom to create anything we want, and it's open to anyone who wants to join in.

In terms of any secrets, it's all about putting ego aside. We see a lot of students on second or third careers, and they may come from extremely aggressive and competitive industries. Since our industry is inclusive, It's all about taking a welcoming approach to their learning needs. Introducing the concept of collaboration and open source early removes the fear of looking stupid when asking questions.

As well, just not taking myself too seriously when teaching. I make mistakes and have brain farts when coding as well. Letting my students see that it's all about the experience helps disarm the fear of failure.

Lastly, I simply love my job. Sharing my passion for this industry with others is huge. I work 12 hour days often and love it, because it doesn't feel like work, it's my life.
