### ISSUE TITLE
What skills are important as an educator?

### ISSUE THREAD

**Issue by sindresorhus** [drewminns/ama#7]

**Comment by drewminns** [comment]
Patience, Empathy, Selflessness and the ability to pick out comfortable shoes.

## Patience

Self-explanatory. Just be patient with learners. You didn't pick up JavaScript in one day, why would anyone else?

## Empathy

Put yourself in their shoes. At HackerYou, we have many students who quit their job and are fully committed to becoming a developer in 9 weeks. That blows my mind, these students are far more passionate than I will ever be. I say this because I've never quit my job to follow something I'm passionate about. That alone allows me to understand their struggles and needs, thus pivoting my teaching style.

## Selflessness

This is such a huge one. Get over yourself. You're there to help people love what you love. It's very easy to tell people what not to do, but you should be telling people what they should do. This industry has opinions, we know that, but keep them to yourself when teaching. CSS Animations aren't my bread and butter, but just because I don't like them, doesn't make them any less important to teach. On the other side of it, I love Flexbox, but that doesn't make floats any less important to teach, or any sites built with it, 'bad'. This is so much more important in design thought - nothing is bad, just celebrate making something.

## Shoes

I'm on my feet all day. I don't have a desk. Nikes for life.
